export interface PromptTemplate {
  systemMessage: string;
  userTemplate: string;
  disclaimer: string;
}

export const promptTemplates: Record<string, PromptTemplate> = {
  'General wellness': {
    systemMessage: 'You are an AI medical assistant designed to help users understand potential health issues based on their symptoms. Provide clear, non-technical language and maintain a supportive, informative tone while avoiding absolute medical claims.',
    userTemplate: `The following symptoms have been shared: {{symptoms}}

Please provide:
1. A potential diagnosis in clear, non-technical language
2. Three practical suggestions for managing symptoms at home
3. Appropriate over-the-counter (OTC) medicine recommendations with general dosage guidelines
4. Follow-up questions to gather more detailed information if needed`,
    disclaimer: 'This response is generated by an AI and is intended for informational purposes only. It is not a substitute for professional medical advice, diagnosis, or treatment. Always consult a licensed healthcare provider before taking any medications or starting any new treatment. If your symptoms persist or worsen, please seek medical attention immediately.'
  },
  'Depression': {
    systemMessage: 'You are an AI assistant focused on providing support for individuals experiencing potential symptoms of depression. Maintain an empathetic, supportive, and non-judgmental tone throughout your response.',
    userTemplate: `The following symptoms have been shared: {{symptoms}}

Please provide:
1. A supportive assessment of how these symptoms may relate to depression
2. Three actionable tips for managing depressive symptoms
3. A 7-day action plan with manageable daily tasks
4. Follow-up questions to better understand the situation
5. Resources for professional mental health support`,
    disclaimer: 'This response is generated by an AI and is intended for informational purposes only. It is not a substitute for professional medical advice, diagnosis, or treatment. Please consult a licensed healthcare provider for any medical concerns. If you are in crisis or need urgent mental health support, please contact a healthcare professional immediately.'
  },
  'Mental health': {
    systemMessage: 'You are an AI assistant designed to support individuals dealing with mental health concerns. Use clear, supportive language and maintain an empathetic tone throughout your response.',
    userTemplate: `The following concerns have been shared: {{symptoms}}

Please provide:
1. A thoughtful assessment of how these symptoms might relate to mental health
2. Three practical strategies for managing symptoms safely
3. A 7-day action plan focusing on gradual improvement
4. Follow-up questions to gather more context
5. Information about when and how to seek professional help`,
    disclaimer: 'This response is generated by an AI and is intended for informational purposes only. It is not a substitute for professional medical advice, diagnosis, or treatment. Please consult a licensed healthcare professional for any medical concerns. If you are in crisis or need urgent mental health support, please contact a mental health professional immediately.'
  }
}